# Test data for missing values
def check_for_na(users, books, new_users, new_books):
    print ()
    print ('User-City: ', users ['User-City'].isna ().sum ())
    print ('User-State: ', users ['User-State'].isna ().sum ())
    print ('User-Country: ', users ['User-Country'].isna ().sum ())
    print ('User-Age: ', users ['User-Age'].isna ().sum ())
    print ()
    print ('Book-Title: ', books ['Book-Title'].isna ().sum ())
    print ('Book-Author: ', books ['Book-Author'].isna ().sum ())
    print ('Year-Of-Publication: ', books ['Year-Of-Publication'].isna ().sum ())
    print ('Book-Publisher: ', books ['Book-Publisher'].isna ().sum ())
    print ()
    print ('New-User-City: ', new_users ['User-City'].isna ().sum ())
    print ('New-User-State: ', new_users ['User-State'].isna ().sum ())
    print ('New-User-Country: ', new_users ['User-Country'].isna ().sum ())
    print ('New-User-Age: ', new_users ['User-Age'].isna ().sum ())
    print ()
    print ('New-Book-Title: ', new_books ['Book-Title'].isna ().sum ())
    print ('New-Book-Author: ', new_books ['Book-Author'].isna ().sum ())
    print ('New-Year-Of-Publication: ', new_books ['Year-Of-Publication'].isna ().sum ())
    print ('New-Book-Publisher: ', new_books ['Book-Publisher'].isna ().sum ())
    print ()
